# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json

package: client
output: pkg/gen/client.go
generate:
  models: true
  client: true
  embedded-spec: true
output-options:
  include-tags:
    - users
