# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json

package: oapi
output: internal/gen/oapi/users.go
generate:
  models: true
  strict-server: true
  gorilla-server: true
  embedded-spec: true
output-options:
  include-tags:
    - users
