version: "2"
sql:
  - engine: "postgresql"
    queries: "../db/queries/"
    schema: "../db/migrations/"
    gen:
      go:
        out: "../internal/gen/db"
        sql_package: "pgx/v5"
        emit_pointers_for_null_types: true
        overrides:
          - db_type: "uuid"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
